/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardsCompanyOwnerCompanyOwnerDashboardLayoutImport } from './routes/dashboards/company-owner/_companyOwnerDashboardLayout'
import { Route as DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseStaffRouteImport } from './routes/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse-staff/route'
import { Route as DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseRouteImport } from './routes/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse/route'
import { Route as DashboardsCompanyOwnerCompanyOwnerDashboardLayoutVehicleRouteImport } from './routes/dashboards/company-owner/_companyOwnerDashboardLayout/vehicle/route'
import { Route as DashboardsCompanyOwnerCompanyOwnerDashboardLayoutShipmentRouteImport } from './routes/dashboards/company-owner/_companyOwnerDashboardLayout/shipment/route'
import { Route as DashboardsCompanyOwnerCompanyOwnerDashboardLayoutFreightCompanyRouteImport } from './routes/dashboards/company-owner/_companyOwnerDashboardLayout/freight-company/route'

// Create Virtual Routes

const DashboardsCompanyOwnerImport = createFileRoute(
  '/dashboards/company-owner',
)()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardsCompanyOwnerRoute = DashboardsCompanyOwnerImport.update({
  path: '/dashboards/company-owner',
  getParentRoute: () => rootRoute,
} as any)

const DashboardsCompanyOwnerCompanyOwnerDashboardLayoutRoute =
  DashboardsCompanyOwnerCompanyOwnerDashboardLayoutImport.update({
    id: '/_companyOwnerDashboardLayout',
    getParentRoute: () => DashboardsCompanyOwnerRoute,
  } as any)

const DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseStaffRouteRoute =
  DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseStaffRouteImport.update(
    {
      path: '/warehouse-staff',
      getParentRoute: () =>
        DashboardsCompanyOwnerCompanyOwnerDashboardLayoutRoute,
    } as any,
  )

const DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseRouteRoute =
  DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseRouteImport.update({
    path: '/warehouse',
    getParentRoute: () =>
      DashboardsCompanyOwnerCompanyOwnerDashboardLayoutRoute,
  } as any)

const DashboardsCompanyOwnerCompanyOwnerDashboardLayoutVehicleRouteRoute =
  DashboardsCompanyOwnerCompanyOwnerDashboardLayoutVehicleRouteImport.update({
    path: '/vehicle',
    getParentRoute: () =>
      DashboardsCompanyOwnerCompanyOwnerDashboardLayoutRoute,
  } as any)

const DashboardsCompanyOwnerCompanyOwnerDashboardLayoutShipmentRouteRoute =
  DashboardsCompanyOwnerCompanyOwnerDashboardLayoutShipmentRouteImport.update({
    path: '/shipment',
    getParentRoute: () =>
      DashboardsCompanyOwnerCompanyOwnerDashboardLayoutRoute,
  } as any)

const DashboardsCompanyOwnerCompanyOwnerDashboardLayoutFreightCompanyRouteRoute =
  DashboardsCompanyOwnerCompanyOwnerDashboardLayoutFreightCompanyRouteImport.update(
    {
      path: '/freight-company',
      getParentRoute: () =>
        DashboardsCompanyOwnerCompanyOwnerDashboardLayoutRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboards/company-owner': {
      id: '/dashboards/company-owner'
      path: '/dashboards/company-owner'
      fullPath: '/dashboards/company-owner'
      preLoaderRoute: typeof DashboardsCompanyOwnerImport
      parentRoute: typeof rootRoute
    }
    '/dashboards/company-owner/_companyOwnerDashboardLayout': {
      id: '/dashboards/company-owner/_companyOwnerDashboardLayout'
      path: '/dashboards/company-owner'
      fullPath: '/dashboards/company-owner'
      preLoaderRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutImport
      parentRoute: typeof DashboardsCompanyOwnerRoute
    }
    '/dashboards/company-owner/_companyOwnerDashboardLayout/freight-company': {
      id: '/dashboards/company-owner/_companyOwnerDashboardLayout/freight-company'
      path: '/freight-company'
      fullPath: '/dashboards/company-owner/freight-company'
      preLoaderRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutFreightCompanyRouteImport
      parentRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutImport
    }
    '/dashboards/company-owner/_companyOwnerDashboardLayout/shipment': {
      id: '/dashboards/company-owner/_companyOwnerDashboardLayout/shipment'
      path: '/shipment'
      fullPath: '/dashboards/company-owner/shipment'
      preLoaderRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutShipmentRouteImport
      parentRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutImport
    }
    '/dashboards/company-owner/_companyOwnerDashboardLayout/vehicle': {
      id: '/dashboards/company-owner/_companyOwnerDashboardLayout/vehicle'
      path: '/vehicle'
      fullPath: '/dashboards/company-owner/vehicle'
      preLoaderRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutVehicleRouteImport
      parentRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutImport
    }
    '/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse': {
      id: '/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse'
      path: '/warehouse'
      fullPath: '/dashboards/company-owner/warehouse'
      preLoaderRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseRouteImport
      parentRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutImport
    }
    '/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse-staff': {
      id: '/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse-staff'
      path: '/warehouse-staff'
      fullPath: '/dashboards/company-owner/warehouse-staff'
      preLoaderRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseStaffRouteImport
      parentRoute: typeof DashboardsCompanyOwnerCompanyOwnerDashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashboardsCompanyOwnerRoute: DashboardsCompanyOwnerRoute.addChildren({
    DashboardsCompanyOwnerCompanyOwnerDashboardLayoutRoute:
      DashboardsCompanyOwnerCompanyOwnerDashboardLayoutRoute.addChildren({
        DashboardsCompanyOwnerCompanyOwnerDashboardLayoutFreightCompanyRouteRoute,
        DashboardsCompanyOwnerCompanyOwnerDashboardLayoutShipmentRouteRoute,
        DashboardsCompanyOwnerCompanyOwnerDashboardLayoutVehicleRouteRoute,
        DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseRouteRoute,
        DashboardsCompanyOwnerCompanyOwnerDashboardLayoutWarehouseStaffRouteRoute,
      }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboards/company-owner"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboards/company-owner": {
      "filePath": "dashboards/company-owner",
      "children": [
        "/dashboards/company-owner/_companyOwnerDashboardLayout"
      ]
    },
    "/dashboards/company-owner/_companyOwnerDashboardLayout": {
      "filePath": "dashboards/company-owner/_companyOwnerDashboardLayout.tsx",
      "parent": "/dashboards/company-owner",
      "children": [
        "/dashboards/company-owner/_companyOwnerDashboardLayout/freight-company",
        "/dashboards/company-owner/_companyOwnerDashboardLayout/shipment",
        "/dashboards/company-owner/_companyOwnerDashboardLayout/vehicle",
        "/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse",
        "/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse-staff"
      ]
    },
    "/dashboards/company-owner/_companyOwnerDashboardLayout/freight-company": {
      "filePath": "dashboards/company-owner/_companyOwnerDashboardLayout/freight-company/route.tsx",
      "parent": "/dashboards/company-owner/_companyOwnerDashboardLayout"
    },
    "/dashboards/company-owner/_companyOwnerDashboardLayout/shipment": {
      "filePath": "dashboards/company-owner/_companyOwnerDashboardLayout/shipment/route.tsx",
      "parent": "/dashboards/company-owner/_companyOwnerDashboardLayout"
    },
    "/dashboards/company-owner/_companyOwnerDashboardLayout/vehicle": {
      "filePath": "dashboards/company-owner/_companyOwnerDashboardLayout/vehicle/route.tsx",
      "parent": "/dashboards/company-owner/_companyOwnerDashboardLayout"
    },
    "/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse": {
      "filePath": "dashboards/company-owner/_companyOwnerDashboardLayout/warehouse/route.tsx",
      "parent": "/dashboards/company-owner/_companyOwnerDashboardLayout"
    },
    "/dashboards/company-owner/_companyOwnerDashboardLayout/warehouse-staff": {
      "filePath": "dashboards/company-owner/_companyOwnerDashboardLayout/warehouse-staff/route.tsx",
      "parent": "/dashboards/company-owner/_companyOwnerDashboardLayout"
    }
  }
}
ROUTE_MANIFEST_END */
